### ISSUE TITLE
Intl::CLDR::Plurals in dependencies is not present

### ISSUE THREAD

**Issue by Altai-man** [alabamenhu/Fluent#2]
See https://github.com/alabamenhu/Fluent/blob/master/META6.json#L13
There is not such a module and it is also not provided by `Intl::CLDR`, is it a typo?

**Comment by alabamenhu** [comment]
This is a hold over from when I had everything in the `Intl::CLDR` module.

I thought I had removed all those old dependencies but seems like i missed
one. I'll have it fixed shortly.

**Comment by Altai-man** [comment]
Thank you very much!

**Comment by alabamenhu** [comment]
Version 0.8.1 should resolve issues with the dependency chain (including a few disabled tests due to some changes in functionality in the chain).  It's a stop-gap measure until the new ground-up rewrite is complete.

Thanks again for the heads up!
